FROM jenkins/jenkins:lts

USER root

COPY --from=docker:24-cli /usr/local/bin/docker /usr/local/bin/docker

COPY --from=docker/compose-bin:latest /docker-compose /usr/local/bin/docker-compose

RUN mkdir -p /usr/lib/docker/cli-plugins && \
    ln -s /usr/local/bin/docker-compose /usr/lib/docker/cli-plugins/docker-compose

ARG DOCKER_GID=999
RUN groupadd -g ${DOCKER_GID} docker || true && \
    usermod -aG docker jenkins

USER jenkins
